### ISSUE TITLE
Catch 2 second timeout exception

### ISSUE THREAD

**Issue by mintingle** [mintingle/appinventor-sources#2]
App crashes when wifi connection is bad due to 2 second timeout. We need to catch the exception and have it wait instead of crash the app. See stack trace below. Check to see if there is a way to do transactions less often.

I/RedCloud(31452): tag nat2draw1TAG_POINTS_LIST is newly set
W/dalvikvm(31452): threadid=11: thread exiting with uncaught exception (group=0x415cddb8)
E/AndroidRuntime(31452): FATAL EXCEPTION: Thread-150474
E/AndroidRuntime(31452): Process: appinventor.ai_test.RedCloudPaintPot_checkpoint4, PID: 31452
**E/AndroidRuntime(31452): redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: failed to connect to /128.52.179.76 (port 6379) after 2000ms**
E/AndroidRuntime(31452):        at redis.clients.jedis.Connection.connect(Connection.java:205)
E/AndroidRuntime(31452):        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:99)
E/AndroidRuntime(31452):        at redis.clients.jedis.Connection.sendCommand(Connection.java:125)
E/AndroidRuntime(31452):        at redis.clients.jedis.Connection.sendCommand(Connection.java:116)
E/AndroidRuntime(31452):        at redis.clients.jedis.BinaryClient.auth(BinaryClient.java:572)
E/AndroidRuntime(31452):        at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2180)
E/AndroidRuntime(31452):        at com.google.appinventor.components.runtime.RedCloud.getJedis(RedCloud.java:416)
E/AndroidRuntime(31452):        at com.google.appinventor.components.runtime.RedCloud.access$000(RedCloud.java:64)
E/AndroidRuntime(31452):        at com.google.appinventor.components.runtime.RedCloud$2.run(RedCloud.java:230)
E/AndroidRuntime(31452): Caused by: java.net.SocketTimeoutException: failed to connect to /128.52.179.76 (port 6379) after 2000ms
E/AndroidRuntime(31452):        at libcore.io.IoBridge.connectErrno(IoBridge.java:159)
E/AndroidRuntime(31452):        at libcore.io.IoBridge.connect(IoBridge.java:112)
E/AndroidRuntime(31452):        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
E/AndroidRuntime(31452):        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
E/AndroidRuntime(31452):        at java.net.Socket.connect(Socket.java:833)
E/AndroidRuntime(31452):        at redis.clients.jedis.Connection.connect(Connection.java:182)
E/AndroidRuntime(31452):        ... 8 more
I/Form    (31452): Form Screen1 got onPause
I/Form    (31452): Form Screen1 got onStop
I/Form    (31452): Form Screen1 got onDestroy

**Comment by mintingle** [comment]
Resolved in commit 5e647f111a0e20ab7576c33b7929d60553ac639d
